### ISSUE TITLE
Does anyone get this exception?  -- Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.

### ISSUE THREAD

**Issue by Alan-Chen-au** [bobcarroll/jira-client#110]
I checked this version two months ago. 
I use jira-client in Multi-thread env.

any suggestion? 
Thanks
Alan

**Comment by Alan-Chen-au** [comment]
more information shown below : 

net.rcarz.jiraclient.JiraException: Failed to retrieve issue PROVSERV-14990
	at net.rcarz.jiraclient.Issue.realGet(Issue.java:1001)
	at net.rcarz.jiraclient.Issue.get(Issue.java:1024)
	at net.rcarz.jiraclient.JiraClient.getIssue(JiraClient.java:99)
	at net.onthenet.jirarest.javaclient.OTNIssue.<init>(OTNIssue.java:76)
	at net.onthenet.dslprovisioning.eo.DslCustomerOrder$JiraDslCancelHandlerThread.run(DslCustomerOrder.java:1162)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:160)
	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:142)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:422)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:129)
	at net.rcarz.jiraclient.RestClient.get(RestClient.java:273)
	at net.rcarz.jiraclient.Issue.realGet(Issue.java:999)

**Comment by Alan-Chen-au** [comment]
solved and updated JiraClient.java

... ...
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.impl.conn.PoolingHttpClientConnectionManager;
... ...

public class JiraClient {

    private RestClient restclient = null;
    private String username = null;
    // Added by Alan Chen for Multi-thread problem
    // Date : 2015/11/09
    private static CloseableHttpClient httpClient = null;
    private static PoolingHttpClientConnectionManager connManager = null;

    /**
     * Creates a JIRA client.
     *
     * @param uri Base URI of the JIRA server
     * @throws JiraException 
     */
    public JiraClient(String uri) throws JiraException {
        this(uri, null);
    }

    /**
     * Creates an authenticated JIRA client.
     *
     * @param uri Base URI of the JIRA server
     * @param creds Credentials to authenticate with
     * @throws JiraException 
     */
    public JiraClient(String uri, ICredentials creds) throws JiraException {
        // Modified by Alan Chen for Muti-thread problem
        // Date : 2015/11/09
        // DefaultHttpClient httpclient = new DefaultHttpClient();
        if (null == httpClient) {
          connManager = new PoolingHttpClientConnectionManager();
          connManager.setDefaultMaxPerRoute(20);
          connManager.setMaxTotal(40);
          httpClient = HttpClients.custom().setConnectionManager(connManager).build();
        }
        
        restclient = new RestClient(httpClient, creds, URI.create(uri));

        if (creds != null) {
            username = creds.getLogonName();
        	//intialize connection if required
        	creds.initialize(restclient);
        }
    }

**Comment by jefdcruz** [comment]
I still get this error, happens when multiple requests are made simultaneously

**Comment by Alan-Chen-au** [comment]
send me your sample code and let me have a look !

**Comment by btiernay** [comment]
What do you think about having a constructor that allows passing in the `HttpClient`?

**Comment by tess1o** [comment]
I'm also getting this issue. I use this library in Spring boot application. I have a Service (scope = prototype) where the jira API is used.  I'm getting the exception only when multiple requests are made simultaneously.

**Comment by Alan-Chen-au** [comment]
net.rcarz:jira-client:0.5 ---> this was previous release; which cannot support this feature. 
Just clone the current one which should be fine.

**Comment by Alan-Chen-au** [comment]
@btiernay It is another option. I believe it is a good way in some scenarios.    
@rcarz may give us more comments I believe.
